name: Lint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:

  #Triggers when a pull request event occurs (opened, synchronize, reopened)
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Fix GitHub Actions crashing with:
    # CRASH: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=1g"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout GIT
        uses: actions/checkout@v2

      - name: Setup Java SDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      #----------------------------------------------------

      #Security
      #      - name: Validate Gradle Wrapper checksum
      #        uses: gradle/wrapper-validation-action@v1
      #
      #      - name: Make Gradle Wrapper (gradlew) executable
      #        run: chmod +x gradlew
      #----------------------------------------------------

      #Optimization
      - name: Enable Gradle Wrapper caching (optmization)
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      #---------------------------------------------------

      # Check: Lint
      - name: Lint
        run: ./gradlew lint

      - name: Upload Lint report to GitHub (see artificats)
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: lint-report.html
          path: app/lint-merged-report.html
      #------------------------------------------------------------------
